#!/bin/sh
while true 
do
echo ""
echo "Menu"
echo "-------------------------------"
echo "0-Wyjście z programu"
echo "1-Z dzięsiętnej na Binarną"
echo "2-Z dziesiętnej na szestnastkową"
echo "-------------------------------"

echo -n "> " 
read a

if [ $a -eq 0 ]
 then echo "Koniec Programu"; 
 exit 4

elif [ $a -eq 1 ]
then
 echo "$a" > dane.txt;
 echo 'Wpisz liczbę dziesiętną:'
 echo -n "> " 
 read b
 echo "$b" > dane.txt
 WYNIK=""
 while [ $WYNIK !="" ]
 do
 WYNIK=`sed -n 1p wyniki.txt`
 done
 echo "" > dane.txt
 echo "" > wyniki.txt
 echo -e '\0033\0143'
 echo "Wynik to: $WYNIK"

elif [ $a -eq 2 ]
then
 echo "$a" > dane.txt;
 echo 'Wpisz liczbę dziesiętną:'
 echo -n "> " 
 read c
 echo "$c" > dane.txt
 WYNIK=""
 while [ $WYNIK !="" ]
 do
 WYNIK=`sed -n 1p wyniki.txt`
 done
 echo "" > dane.txt
 echo "" > wyniki.txt
 echo -e '\0033\0143'
 echo "Wynik to: $WYNIK"

else 
 echo -e '\0033\0143'
 echo "Niewłaściwy wybór. Spróbuj jeszcze raz."

fi
done
